### ISSUE TITLE
Model 4P cannot boot Model III OS

### ISSUE THREAD

**Issue by TJBChris** [TJBChris/FreHDDisk#3]
Because the 4P lacks the Model III ROMs, Model III OSes fail to boot on a Model 4P.  Can the disk be updated to load the Model III ROM image (or coax the 4P to do it as it does for other OSes)?

**Comment by drjohnnyfever1** [comment]
I'm interested in getting this working. Still waiting for my frehd in the mail.

Is it possible to run FREHD/CMD from LDOS with the 4p already in model III mode?

**Comment by TJBChris** [comment]
Thanks for sharing your interest.  You can run FREHD/CMD from LDOS, but it'll crash if you try to boot back into LDOS.  Model 4 OSes seem to work if you run FREHD/CMD from LDOS.  

It's really meant to be run from the boot sector (this is based on a BASIC program to be run from ROM BASIC on systems without the FreHD auto boot ROM); FREHD/CMD was just the place for the assembler to put its output and a place from which I could get the assembled code to stick into the boot sector of the disks when I was making them.  It may be a bit before this is working; I'm amid a few other projects.  But this issue will help me track progress and interest.  

It's also worth nothing the BASIC program these disks are based on crashes on a 4P just like the disks if you load the Model III BASIC ROM into the 4P, restart into Model III BASIC, run the BASIC program and select LDOS from the menu (at least in trs80gp).  That implies the frehd boot code in ROM works together with the code in the frehd.rom file to make it play nice on the 4P, but I haven't had the chance to dig yet.

**Comment by TJBChris** [comment]
This should be resolved with release 1.1.  I do not have a real 4P; trs80gp works.  If issues arise, a new issue will be created.
